/*
  Copyright (C) 2018-2026 by the authors of the World Builder code.

  This file is part of the World Builder.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Lesser General Public License as published
   by the Free Software Foundation, either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "world_builder/features/oceanic_plate_models/composition/perlin_noise.h"

#include "world_builder/nan.h"
#include "world_builder/types/array.h"
#include "world_builder/types/double.h"
#include "world_builder/types/object.h"
#include "world_builder/types/one_of.h"
#include "world_builder/types/string.h"
#include "world_builder/types/unsigned_int.h"
#include "world_builder/types/value_at_points.h"
#include "world_builder/world.h"
#include <algorithm>
#include <cmath>
#include <numeric>
#include <random>

namespace WorldBuilder
{
  using namespace Utilities;

  namespace Features
  {
    using namespace FeatureUtilities;
    namespace OceanicPlateModels
    {
      namespace Composition
      {
        PerlinNoise::PerlinNoise(WorldBuilder::World *world_)
          :
          min_depth(NaN::DSNAN),
          max_depth(NaN::DSNAN),
          operation(Operations::ADD)
        {
          this->world = world_;
          this->name = "perlin_noise";

          // Initialize permutation table
          std::iota(p.begin(), p.end(), 0);
        }

        PerlinNoise::~PerlinNoise() = default;

        void
        PerlinNoise::declare_entries(Parameters &prm, const std::string &)
        {
          // Document plugin and require entries if needed.
          // Add compositions to the required parameters.
          prm.declare_entry("", Types::Object({"compositions"}),
                            "Perlin noise composition model. Generates values in a range.");

          // Declare entries of this plugin

          prm.declare_entry("min depth", Types::OneOf(Types::Double(0),
                                                      Types::Array(Types::ValueAtPoints(0.,2)),
                                                      Types::String("")),
                            "The depth in meters from which the composition of this feature is present.");

          prm.declare_entry("max depth", Types::OneOf(Types::Double(std::numeric_limits<double>::max()),
                                                      Types::Array(Types::ValueAtPoints(std::numeric_limits<double>::max(),2)),
                                                      Types::String("")),
                            "The depth in meters to which the composition of this feature is present.");

          prm.declare_entry("compositions", Types::Array(Types::UnsignedInt(),0),
                            "A list with labels of compositions present.");
          prm.declare_entry("min value", Types::Array(Types::Double(0.0),1),
                            "Minimum value generated by Perlin noise.");
          prm.declare_entry("max value", Types::Array(Types::Double(1.0),1),
                            "Maximum value generated by Perlin noise.");
          prm.declare_entry("frequency", Types::Double(1.0), "Frequency of the Perlin noise.");
          prm.declare_entry("octaves", Types::UnsignedInt(1), "Number of octaves for the Perlin noise.");
          prm.declare_entry("persistence", Types::Double(0.5), "Amplitude multiplier between octaves.");
          prm.declare_entry("lacunarity", Types::Double(2.0), "Frequency multiplier between octaves.");
          prm.declare_entry("operation", Types::String("add", std::vector<std::string> {"replace", "replace defined only", "add", "subtract"}),
                            "Whether to replace, add, or subtract values.");
        }

        void
        PerlinNoise::parse_entries(Parameters &prm, const std::vector<Point<2>> &coordinates)
        {
          min_depth_surface = Objects::Surface(prm.get("min depth", coordinates));
          min_depth = min_depth_surface.minimum;
          max_depth_surface = Objects::Surface(prm.get("max depth", coordinates));
          max_depth = max_depth_surface.maximum;

          compositions = prm.get_vector<unsigned int>("compositions");
          min_value = prm.get_vector<double>("min value");
          max_value = prm.get_vector<double>("max value");
          frequency = prm.get<double>("frequency");
          octaves = prm.get<unsigned int>("octaves");
          persistence = prm.get<double>("persistence");
          lacunarity = prm.get<double>("lacunarity");
          std::shuffle(p.begin(), p.end(), world->get_random_number_engine());
          operation = string_operations_to_enum(prm.get<std::string>("operation"));
        }

        double
        PerlinNoise::get_composition(const Point<3> &position,
                                     const Objects::NaturalCoordinate &position_in_natural_coordinates,
                                     const double depth,
                                     const unsigned int composition_number,
                                     double composition,
                                     const double,
                                     const double) const
        {
          if (depth <= max_depth && depth >= min_depth)
            {
              const double min_depth_local = min_depth_surface.constant_value ? min_depth : min_depth_surface.local_value(position_in_natural_coordinates.get_surface_point()).interpolated_value;
              const double max_depth_local = max_depth_surface.constant_value ? max_depth : max_depth_surface.local_value(position_in_natural_coordinates.get_surface_point()).interpolated_value;
              if (depth <= max_depth_local && depth >= min_depth_local)
                {
                  for (const unsigned int i : compositions)
                    {
                      if (i == composition_number)
                        {
                          const double noise_val = octave_noise(position[0], position[1], position[2], octaves);
                          const double composition_ = min_value[0] + (noise_val * 0.5 + 0.5) * (max_value[0] - min_value[0]);
                          return apply_operation(operation, composition, composition_);
                        }
                    }

                  if (operation == Operations::REPLACE)
                    return 0.0;
                }
            }
          return composition;
        }

        double
        PerlinNoise::fade(double t) const
        {
          return t * t * t * (t * (t * 6 - 15) + 10);
        }
        double
        PerlinNoise::lerp(double t, double a, double b) const
        {
          return a + t * (b - a);
        }
        double
        PerlinNoise::grad(int hash, double x, double y, double z) const
        {
          const int h = hash & 15;
          const double u = h < 8 ? x : y;
          const double v = h < 4 ? y : h == 12 || h == 14 ? x : z;
          return ((h & 1) == 0 ? u : -u) + ((h & 2) == 0 ? v : -v);
        }

        double
        PerlinNoise::noise(double x, double y, double z) const
        {
          const int X = static_cast<int>(std::floor(x)) & 255;
          const int Y = static_cast<int>(std::floor(y)) & 255;
          const int Z = static_cast<int>(std::floor(z)) & 255;
          x -= std::floor(x);
          y -= std::floor(y);
          z -= std::floor(z);
          const double u = fade(x);
          const double v = fade(y);
          const double w = fade(z);

          auto perm = [this](const int idx) -> int { return p[idx & 255]; };
          const int A = perm(X) + Y;
          const int AA = perm(A) + Z;
          const int AB = perm(A + 1) + Z;
          const int B = perm(X + 1) + Y;
          const int BA = perm(B) + Z;
          const int BB = perm(B + 1) + Z;

          return lerp(w, lerp(v, lerp(u, grad(perm(AA), x, y, z),
                                      grad(perm(BA), x - 1, y, z)),
                              lerp(u, grad(perm(AB), x, y - 1, z),
                                   grad(perm(BB), x - 1, y - 1, z))),
                      lerp(v, lerp(u, grad(perm(AA + 1), x, y, z - 1),
                                   grad(perm(BA + 1), x - 1, y, z - 1)),
                           lerp(u, grad(perm(AB + 1), x, y - 1, z - 1),
                                grad(perm(BB + 1), x - 1, y - 1, z - 1))));
        }

        double
        PerlinNoise::octave_noise(double x, double y, double z, unsigned int octaves_in) const
        {
          if (octaves_in == 0)
            return 0;

          double total = 0;
          double frequency_local = frequency;
          double amplitude = 1;
          double max_value_local = 0;
          for (unsigned int i = 0; i < octaves_in; ++i)
            {
              total += noise(x * frequency_local, y * frequency_local, z * frequency_local) * amplitude;
              max_value_local += amplitude;
              amplitude *= persistence;
              frequency_local *= lacunarity;
            }

          if (max_value_local <= 0.0)
            return 0;

          return total / max_value_local;
        }

        WB_REGISTER_FEATURE_OCEANIC_PLATE_COMPOSITION_MODEL(PerlinNoise, perlin_noise)
      }
    }
  }
}

