name: benchmark_2

on: [pull_request]

jobs:
  benchmarks:
    strategy: 
      fail-fast: false
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable


    - name: cmake version
      run: cmake --version

    - name: Checkout cbdr
      uses: actions/checkout@v2
      with:
        repository: MFraters/cbdr
        ref: github_actions_fix
        path: cbdr

    - name: retrieve cache cbdr
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/git/
          target/
          ./target/
          ${{github.workspace}}/cbdr/
          ${{github.workspace}}/cbdr/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: retrieve cache master
      uses: actions/cache@v2
      with:
        path: |
          ${{github.workspace}}/master/
        key: ${{ runner.os }}-gwb-master-v3}}


    - name: retrieve cache feature
      uses: actions/cache@v2
      with:
        path: |
          ${{github.workspace}}/feature/
        key: ${{ runner.os }}-gwb-feature-${{ github.event.number }}-v3}}

    - name: Checkout cbdr
      uses: actions/checkout@v2
      with:
        repository: MFraters/cbdr
        ref: github_actions_fix
        path: cbdr
        clean: false


    - name: Checkout feature
      uses: actions/checkout@v2
      with:
        path: feature/source
        clean: false

    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        path: master/source
        clean: false

    - name: cd Build Environment
      run: |
            cd ${{github.workspace}}/cbdr/;
            cargo build --release;



    - name: Create Build Environment
      run: |
            sudo apt install ninja-build;
            cmake -E make_directory ${{github.workspace}}/master/build;

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/master/build
      run: |
            pwd;
            ls;
            cmake  -G"Ninja" $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-Werror -DWB_INCLUDE_UNIT_TEST=FALSE ${{github.workspace}}/master/source/;

    - name: Build gwb
      working-directory: ${{github.workspace}}/master/build
      shell: bash
      run: ninja


    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/feature/build

    - name: cd Build Environment
      run: cd ${{github.workspace}}/feature/build;

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/feature/build
      run: |
            pwd;
            ls;
            cmake -G"Ninja" $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-Werror -DWB_INCLUDE_UNIT_TEST=FALSE ${{github.workspace}}/feature/source/;

    - name: Build gwb
      working-directory: ${{github.workspace}}/feature/build
      shell: bash
      run: ninja

    - name: prepare benchmarks
      shell: bash
      run: |
            cd ${{github.workspace}}/cbdr/;
            mkdir -p ${{github.workspace}}/benchmark_2_results/;

    - name: run benchmark 2
      env:
        benchmark_number: 2
        benchmark_name: slab_interpolation_simple_curved_none
        benchmark_gridfile: cartesian_subducting_plate_gridfile
      shell: bash
      run: |
            cd ${{github.workspace}}/cbdr/;
            time cargo run --release sample --timeout=600s "master:${{github.workspace}}/master/build/bin/./WorldBuilderVisualization  ${{github.workspace}}/feature/source/tests/app/${{env.benchmark_name}}.wb ${{github.workspace}}/feature/source/tests/visualization/${{env.benchmark_gridfile}}.grid" "feature:${{github.workspace}}/feature/build/bin/./WorldBuilderVisualization ${{github.workspace}}/feature/source/tests/app/${{env.benchmark_name}}.wb ${{github.workspace}}/feature/source/tests/visualization/${{env.benchmark_gridfile}}.grid" > ${{github.workspace}}/result_${{env.benchmark_number}}.csv;
            cat ${{github.workspace}}/result_${{env.benchmark_number}}.csv;
            cat ${{github.workspace}}/result_${{env.benchmark_number}}.csv | cargo run --release analyze --disable-dynamic-printing > ${{github.workspace}}/benchmark_2_results/analyze_${{env.benchmark_number}}.log ||:;
            cat ${{github.workspace}}/benchmark_2_results/analyze_${{env.benchmark_number}}.log

    - uses: actions/upload-artifact@v2
      with:
        name: benchmark_2_results
        path: benchmark_2_results/
